export default {
  title: "US Prediction Markets",
  base: "/kalshi-dashboard/",
  root: "src",
  theme: ["air", "near-midnight"],
  style: "styles.css",
  head: '<link rel="preconnect" href="https://rsms.me/">\n<link rel="stylesheet" href="https://rsms.me/inter/inter.css">',
  pages: [
    {name: "Overview", path: "/"},
    {name: "Kalshi Volume", path: "/volume"},
    {name: "Fee Revenue", path: "/fees"},
    {name: "Categories", path: "/categories"},
    {name: "Parlay P&L", path: "/parlay"},
    {name: "Calibration", path: "/calibration"},
    {name: "Platform Comparison", path: "/competitors"},
    {name: "Polymarket US", path: "/polymarket"},
    {name: "ForecastEx", path: "/forecastex"},
    {name: "Crypto.com/Nadex", path: "/nadex"},
  ],
  footer: "Data: Kalshi trade records via Daniel O'Boyle. Updated nightly.",
};
